#!/bin/bash

echo "Hi, I'm a simple program that will help you to check the operation of some internet services"

echo "Enter 1 to view network settings"
echo "Enter 2 to test the router"
echo "Enter 3 to test the DNS service"
echo "Enter 4 to verify site access"

read num
case $num in
1)
	ifconfig;;
2)
	ping -c 4 192.168.1.1;;
3)
	ping -c 4 8.8.8.8 || ping -c 4 8.8.4.4;;
4)
	echo "Enter ip or site name"
	read var

	if ping -c 4 $var
	then
		echo "Site is available"
	else
		echo "site not available"
	fi;;
*)
	echo "The entered data does not correspond to the functionality";;
esac
